//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Email {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Email() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Email", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &lt;table width=&quot;100%&quot; cellspacing=&quot;0&quot; cellpadding=&quot;10&quot; border=&quot;0&quot;&gt;
        ///&lt;tr style=&quot;background-color:#1c5289&quot;&gt;
        ///&lt;td style=&quot;color:#ffffff&quot;&gt;&lt;h2&gt;» Un nouveau compte d&apos;utilisateur a été créé&lt;/h2&gt;&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;{0} vient de créer un compte.&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;Cliquez &lt;a href=&quot;{1}&quot;&gt;ici&lt;/a&gt; pour gérer le compte de {0}.&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td style=&quot;border-top:1px solid #000000&quot;&gt;
        ///&lt;span style=&quot;font-size:12px;font-style:italic&quot;&gt;Ceci est un [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdminConfirmAccountContent {
            get {
                return ResourceManager.GetString("AdminConfirmAccountContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IJP Reporting: Un nouveau compte d&apos;utilisateur a été créé.
        /// </summary>
        internal static string AdminConfirmAccountSubject {
            get {
                return ResourceManager.GetString("AdminConfirmAccountSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;envoyer!.
        /// </summary>
        internal static string AlertSendEmailFailTitle {
            get {
                return ResourceManager.GetString("AlertSendEmailFailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &lt;table width=&quot;100%&quot; cellspacing=&quot;0&quot; cellpadding=&quot;10&quot; border=&quot;0&quot;&gt;
        ///&lt;tr style=&quot;background-color:#1c5289&quot;&gt;
        ///&lt;td style=&quot;color:#ffffff&quot;&gt;&lt;h2&gt;» Confirmer votre compte&lt;/h2&gt;&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;S&apos;il vous plait, confirmez votre compte en cliquant &lt;a href=&quot;{0}&quot;&gt;ici&lt;/a&gt;.&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td style=&quot;border-top:1px solid #000000&quot;&gt;
        ///&lt;span style=&quot;font-size:12px;font-style:italic&quot;&gt;Ceci est un courriel généré par le système, veuillez ne pas y répondre.&lt;/span&gt;
        ///&lt;/td&gt;
        ///&lt;/tr&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConfirmAccountContent {
            get {
                return ResourceManager.GetString("ConfirmAccountContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IJP Reporting: confirmer votre compte.
        /// </summary>
        internal static string ConfirmAccountSubject {
            get {
                return ResourceManager.GetString("ConfirmAccountSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &lt;table width=&quot;100%&quot; cellspacing=&quot;0&quot; cellpadding=&quot;10&quot; border=&quot;0&quot;&gt;
        ///&lt;tr style=&quot;background-color:#1c5289&quot;&gt;
        ///&lt;td style=&quot;color:#ffffff&quot;&gt;&lt;h2&gt;» Réinitialiser votre mot de passe&lt;/h2&gt;&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;S&apos;il vous plait, appuyez &lt;a href=&quot;{0}&quot;&gt;ici&lt;/a&gt; pour réinitialiser votre mot de passe.&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td style=&quot;border-top:1px solid #000000&quot;&gt;
        ///&lt;span style=&quot;font-size:12px;font-style:italic&quot;&gt;Ceci est un courriel généré par le système, veuillez ne pas y répondre. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResetPasswordContent {
            get {
                return ResourceManager.GetString("ResetPasswordContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IJP Reporting: réinitialiser votre mot de passe.
        /// </summary>
        internal static string ResetPasswordSubject {
            get {
                return ResourceManager.GetString("ResetPasswordSubject", resourceCulture);
            }
        }
    }
}
