//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actif.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue, veuillez essayer de nouveau. Si l&apos;erreur persiste, veuillez contacter le support technique..
        /// </summary>
        internal static string AlertErrorContent {
            get {
                return ResourceManager.GetString("AlertErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue!.
        /// </summary>
        internal static string AlertErrorTitle {
            get {
                return ResourceManager.GetString("AlertErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format invalide!.
        /// </summary>
        internal static string AlertInvalidFormatTitle {
            get {
                return ResourceManager.GetString("AlertInvalidFormatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre courriel ou mot de passe n&apos;est pas valide..
        /// </summary>
        internal static string AlertInvalidLoginContent {
            get {
                return ResourceManager.GetString("AlertInvalidLoginContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de vous connecter!.
        /// </summary>
        internal static string AlertInvalidLoginTitle {
            get {
                return ResourceManager.GetString("AlertInvalidLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les mots de passe doivent contenir un minimum de huit (8) caractères alphanumérique. Les mots de passe doivent avoir au moins une lettre majuscule ( &apos;A&apos; – &apos;Z&apos;), une lettre miniscule ( &apos;a&apos; - &apos;z&apos;), un caractère spécial (exemple: &apos;@&apos;, &apos;&amp;&apos;, &apos;*&apos;) et un chiffre ( &apos;0&apos; - &apos;9&apos;)..
        /// </summary>
        internal static string AlertInvalidPasswordContent {
            get {
                return ResourceManager.GetString("AlertInvalidPasswordContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe n&apos;est pas valide.
        /// </summary>
        internal static string AlertInvalidPasswordTitle {
            get {
                return ResourceManager.GetString("AlertInvalidPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur s&apos;est produite lors de l&apos;envoie du courriel..
        /// </summary>
        internal static string AlertSendErrorContent {
            get {
                return ResourceManager.GetString("AlertSendErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;envoyer le courriel!.
        /// </summary>
        internal static string AlertSendErrorTitle {
            get {
                return ResourceManager.GetString("AlertSendErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour continuer, vous devez d&apos;abord vous enregistrer.&lt;br /&gt;&lt;a href=&quot;{0}&quot;&gt;Connectez-vous!&lt;/a&gt;.
        /// </summary>
        internal static string AlertSignInContent {
            get {
                return ResourceManager.GetString("AlertSignInContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectez-vous!.
        /// </summary>
        internal static string AlertSignInTitle {
            get {
                return ResourceManager.GetString("AlertSignInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un ou plusieurs champs sont invalide, veuillez vérifier les champs..
        /// </summary>
        internal static string AlertSomeFieldsNotValidContent {
            get {
                return ResourceManager.GetString("AlertSomeFieldsNotValidContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champs invalide!.
        /// </summary>
        internal static string AlertSomeFieldsNotValidTitle {
            get {
                return ResourceManager.GetString("AlertSomeFieldsNotValidTitle", resourceCulture);
            }
        }
    }
}
