//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJPReporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Form_Type()
        {
            this.Conditions = new HashSet<Conditions>();
            this.Forms = new HashSet<Forms>();
            this.Section_Conditions = new HashSet<Section_Conditions>();
            this.Section = new HashSet<Section>();
            this.Questions = new HashSet<Questions>();
        }
    
        public int FormTypeId { get; set; }
        public string FormTitle_fr { get; set; }
        public string FormTitle_en { get; set; }
        public string FormDescription_fr { get; set; }
        public string FormDescription_en { get; set; }
        public string FormNote_fr { get; set; }
        public string FormNote_en { get; set; }
        public System.Guid CreatorId { get; set; }
        public bool IsObsolete { get; set; }
        public System.DateTime Date_creation { get; set; }
        public Nullable<System.DateTime> Date_updated { get; set; }
        public bool IsDisabled { get; set; }
        public Nullable<int> FormOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conditions> Conditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Forms> Forms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Section_Conditions> Section_Conditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Section> Section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Questions> Questions { get; set; }
    }
}
