//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJPReporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Forms()
        {
            this.UserResponses = new HashSet<UserResponses>();
            this.Regions = new HashSet<Regions>();
        }
    
        public System.Guid form_id { get; set; }
        public string note_fr { get; set; }
        public string note_en { get; set; }
        public bool isFinal { get; set; }
        public bool isObsolete { get; set; }
        public bool isDisabled { get; set; }
        public System.DateTime date_creation { get; set; }
        public Nullable<System.DateTime> date_updated { get; set; }
        public string creator_id { get; set; }
        public int FormType_id { get; set; }
        public string ClientFileNumberId { get; set; }
        public Nullable<int> AcceptStatusId { get; set; }
        public Nullable<int> ComplStatusId { get; set; }
        public System.DateTime RefDate { get; set; }
        public Nullable<int> program_id { get; set; }
        public Nullable<int> community_id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Community Community { get; set; }
        public virtual Programs Programs { get; set; }
        public virtual Status Status { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual Status Status2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserResponses> UserResponses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Regions> Regions { get; set; }
        public virtual Form_Type Form_Type { get; set; }
    }
}
