//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJPReporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Questions()
        {
            this.Conditions = new HashSet<Conditions>();
            this.ReponseChoices = new HashSet<ReponseChoices>();
            this.SubQuestions = new HashSet<SubQuestions>();
            this.UserResponses = new HashSet<UserResponses>();
        }
    
        public System.Guid question_id { get; set; }
        public int question_type_id { get; set; }
        public string libelle_fr { get; set; }
        public string libelle_en { get; set; }
        public int responses_min { get; set; }
        public int responses_max { get; set; }
        public Nullable<int> ordre { get; set; }
        public bool isObsolete { get; set; }
        public System.DateTime date_creation { get; set; }
        public System.Guid creator_id { get; set; }
        public int NoQuestion { get; set; }
        public string Note_fr { get; set; }
        public string Note_en { get; set; }
        public int Section_Id { get; set; }
        public bool IsConditional { get; set; }
        public bool IsMandatory { get; set; }
        public bool IsSubQuestion { get; set; }
        public string TagId { get; set; }
        public int FormTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conditions> Conditions { get; set; }
        public virtual Form_Type Form_Type { get; set; }
        public virtual QuestionTypes QuestionTypes { get; set; }
        public virtual Section Section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReponseChoices> ReponseChoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubQuestions> SubQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserResponses> UserResponses { get; set; }
    }
}
