//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJPReporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReponseChoices
    {
        public System.Guid response_choice_id { get; set; }
        public string text_fr { get; set; }
        public string text_en { get; set; }
        public System.Guid question_id { get; set; }
        public Nullable<int> ordre { get; set; }
        public bool isObsolete { get; set; }
        public System.DateTime creation_date { get; set; }
        public System.Guid creator_id { get; set; }
        public string value { get; set; }
        public bool disabled { get; set; }
        public string tagId { get; set; }
    
        public virtual Questions Questions { get; set; }
    }
}
