//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJPReporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section_Conditions
    {
        public int sectCond_id { get; set; }
        public System.Guid form_id { get; set; }
        public int section_id { get; set; }
        public int action_id { get; set; }
        public int operator_id { get; set; }
        public int form_type_id { get; set; }
        public int regionid { get; set; }
        public string note { get; set; }
        public bool is_disabled { get; set; }
    
        public virtual Actions Actions { get; set; }
        public virtual Form_Type Form_Type { get; set; }
        public virtual Operators Operators { get; set; }
        public virtual Regions Regions { get; set; }
        public virtual Section Section { get; set; }
    }
}
